"""Git hooks integration - Show relevant facts before commit.

Configuration (config.yaml):
    integrations:
      git:
        enabled: true
        suggest_facts_on_commit: true
        auto_tag_commits: false
        pre_commit:
          check_stale_facts: true
          suggest_related: true

Installation:
    memoriq git-install-hooks  # Installs to current repo
    memoriq git-install-hooks --global  # Installs to core.hooksPath
"""

import argparse
import logging
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

from .bus import get_bus

try:
    import sys
    sys.path.insert(0, str(Path(__file__).parent.parent / "mcp-server"))
    from db import open_db_fast
    HAS_DB = True
except ImportError:
    HAS_DB = False

logger = logging.getLogger("memoriq.integrations.git_hooks")

# Hook script template
PRE_COMMIT_HOOK_TEMPLATE = '''#!/bin/bash
# Memoriq Git Hook - Pre-Commit
# Auto-generated by `memoriq git-install-hooks`

# Run Memoriq pre-commit check
python -m integrations.git_hooks run-pre-commit || true

# Exit successfully (we never block commits, just inform)
exit 0
'''

POST_COMMIT_HOOK_TEMPLATE = '''#!/bin/bash
# Memoriq Git Hook - Post-Commit
# Auto-generated by `memoriq git-install-hooks`

# Emit commit event to Memoriq
python -m integrations.git_hooks emit-commit "$@" || true

exit 0
'''


def _load_config() -> dict:
    """Load Git integration config."""
    import yaml

    config_path = Path.home() / ".memoriq" / "config.yaml"
    if not config_path.exists():
        return {}

    try:
        with open(config_path, "r", encoding="utf-8") as f:
            config = yaml.safe_load(f)
            return config.get("integrations", {}).get("git", {})
    except Exception as e:
        logger.error(f"Failed to load config: {e}")
        return {}


def _get_git_root() -> Path | None:
    """Get the root of the current git repository."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=True,
        )
        return Path(result.stdout.strip())
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def _get_staged_files() -> list[str]:
    """Get list of staged files for the current commit."""
    try:
        result = subprocess.run(
            ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"],
            capture_output=True,
            text=True,
            check=True,
        )
        return [f.strip() for f in result.stdout.split("\n") if f.strip()]
    except (subprocess.CalledProcessError, FileNotFoundError):
        return []


def _get_file_mtime(filepath: str) -> float | None:
    """Get modification time of a file."""
    git_root = _get_git_root()
    if not git_root:
        return None

    full_path = git_root / filepath
    if full_path.exists():
        return full_path.stat().st_mtime
    return None


def _get_facts_for_file(filepath: str, project: str) -> list[dict]:
    """Get facts related to a specific file."""
    if not HAS_DB:
        return []

    db = open_db_fast()
    try:
        # Match by source_file
        rows = db.execute(
            """
            SELECT id, content, timestamp, source_mtime, tags, type
            FROM facts
            WHERE project = ? AND source_file = ?
            ORDER BY timestamp DESC
            """,
            (project, filepath),
        ).fetchall()
        return [dict(row) for row in rows]
    except Exception as e:
        logger.debug(f"Failed to query facts for {filepath}: {e}")
        return []
    finally:
        db.close()


def _is_fact_stale(fact: dict, current_mtime: float | None) -> bool:
    """Check if a fact is stale (file modified after fact was created)."""
    if current_mtime is None:
        return False

    fact_mtime = fact.get("source_mtime")
    if fact_mtime is None:
        return False

    # Compare timestamps
    try:
        return float(fact_mtime) < current_mtime
    except (TypeError, ValueError):
        return False


def _get_related_facts(files: list[str], project: str) -> list[dict]:
    """Get facts related to the changed files (by tags/content similarity)."""
    if not HAS_DB or not files:
        return []

    # Extract keywords from filenames
    keywords = set()
    for f in files:
        # Get basename without extension
        name = Path(f).stem
        # Split by common separators
        parts = name.replace("-", "_").split("_")
        keywords.update(p.lower() for p in parts if len(p) > 2)

    if not keywords:
        return []

    db = open_db_fast()
    try:
        # Build FTS query from keywords
        fts_terms = list(keywords)[:5]
        fts_query = " OR ".join(fts_terms)

        rows = db.execute(
            """
            SELECT f.id, f.content, f.timestamp, f.tags, f.type
            FROM facts f
            JOIN facts_fts fts ON f.rowid = fts.rowid
            WHERE fts.facts_fts MATCH ? AND f.project = ?
            LIMIT 20
            """,
            (fts_query, project),
        ).fetchall()

        return [dict(row) for row in rows]
    except Exception as e:
        logger.debug(f"Failed to query related facts: {e}")
        return []
    finally:
        db.close()


def _format_fact_preview(content: str, max_len: int = 80) -> str:
    """Format a fact content preview."""
    lines = content.split("\n")
    first_line = lines[0].strip()
    if len(first_line) > max_len:
        return first_line[:max_len].rstrip() + "..."
    return first_line


def run_pre_commit() -> int:
    """Run pre-commit checks. Outputs to stderr.

    Returns:
        Exit code (always 0, we never block commits)
    """
    config = _load_config()

    if not config.get("enabled", False):
        return 0

    if not config.get("suggest_facts_on_commit", True):
        return 0

    # Get project name from git root
    git_root = _get_git_root()
    if not git_root:
        print("[Memoriq] Not in a git repository", file=sys.stderr)
        return 0

    project = git_root.name
    staged_files = _get_staged_files()

    if not staged_files:
        return 0

    check_stale = config.get("pre_commit", {}).get("check_stale_facts", True)
    suggest_related = config.get("pre_commit", {}).get("suggest_related", True)

    output_lines = ["[Memoriq] Facts related to your changes:"]
    has_output = False

    # Check each staged file
    for filepath in staged_files:
        file_output = []
        current_mtime = _get_file_mtime(filepath)

        # Get facts for this file
        facts = _get_facts_for_file(filepath, project)

        for fact in facts:
            preview = _format_fact_preview(fact["content"])
            fact_date = fact.get("timestamp", "")[:10]

            if check_stale and _is_fact_stale(fact, current_mtime):
                file_output.append(
                    f'    \u26a0 STALE: "{preview}" (fact from {fact_date})'
                )
                file_output.append(
                    "    \u2192 Consider running /harvest to update"
                )
            else:
                file_output.append(f'    \u2022 "{preview}" ({fact_date})')

        if file_output:
            has_output = True
            output_lines.append(f"\n  {filepath}:")
            output_lines.extend(file_output)

    # Get related facts by content similarity
    if suggest_related:
        related = _get_related_facts(staged_files, project)
        if related:
            has_output = True
            output_lines.append("\n  Related knowledge:")
            for fact in related[:5]:  # Limit to top 5
                preview = _format_fact_preview(fact["content"], 60)
                fact_type = fact.get("type", "fact")
                output_lines.append(f'    \ud83d\udca1 {fact_type}: "{preview}"')

    if has_output:
        print("\n".join(output_lines), file=sys.stderr)
        print("", file=sys.stderr)  # Empty line for separation

    return 0


def install_hooks(repo_path: Path | None = None, global_install: bool = False) -> dict:
    """Install Memoriq git hooks.

    Args:
        repo_path: Path to git repository (None for current directory)
        global_install: If True, install to core.hooksPath

    Returns:
        Dict with installation results
    """
    if global_install:
        # Get global hooks path
        try:
            result = subprocess.run(
                ["git", "config", "--global", "core.hooksPath"],
                capture_output=True,
                text=True,
            )
            if result.returncode == 0 and result.stdout.strip():
                hooks_dir = Path(result.stdout.strip()).expanduser()
            else:
                # Set a default global hooks path
                hooks_dir = Path.home() / ".git-hooks"
                subprocess.run(
                    ["git", "config", "--global", "core.hooksPath", str(hooks_dir)],
                    check=True,
                )
        except (subprocess.CalledProcessError, FileNotFoundError) as e:
            return {"success": False, "error": f"Failed to get global hooks path: {e}"}
    else:
        # Local repo hooks
        if repo_path is None:
            git_root = _get_git_root()
            if not git_root:
                return {"success": False, "error": "Not in a git repository"}
            repo_path = git_root

        hooks_dir = repo_path / ".git" / "hooks"

    # Ensure hooks directory exists
    hooks_dir.mkdir(parents=True, exist_ok=True)

    installed = []

    # Install pre-commit hook
    pre_commit_path = hooks_dir / "pre-commit"
    try:
        with open(pre_commit_path, "w", encoding="utf-8") as f:
            f.write(PRE_COMMIT_HOOK_TEMPLATE)
        pre_commit_path.chmod(0o755)
        installed.append("pre-commit")
    except Exception as e:
        return {"success": False, "error": f"Failed to install pre-commit hook: {e}"}

    # Install post-commit hook
    post_commit_path = hooks_dir / "post-commit"
    try:
        with open(post_commit_path, "w", encoding="utf-8") as f:
            f.write(POST_COMMIT_HOOK_TEMPLATE)
        post_commit_path.chmod(0o755)
        installed.append("post-commit")
    except Exception as e:
        return {"success": False, "error": f"Failed to install post-commit hook: {e}"}

    return {
        "success": True,
        "installed": installed,
        "hooks_dir": str(hooks_dir),
        "global": global_install,
    }


def uninstall_hooks(repo_path: Path | None = None, global_install: bool = False) -> dict:
    """Uninstall Memoriq git hooks.

    Args:
        repo_path: Path to git repository (None for current directory)
        global_install: If True, uninstall from core.hooksPath

    Returns:
        Dict with uninstallation results
    """
    if global_install:
        try:
            result = subprocess.run(
                ["git", "config", "--global", "core.hooksPath"],
                capture_output=True,
                text=True,
            )
            if result.returncode == 0 and result.stdout.strip():
                hooks_dir = Path(result.stdout.strip()).expanduser()
            else:
                hooks_dir = Path.home() / ".git-hooks"
        except (subprocess.CalledProcessError, FileNotFoundError):
            return {"success": False, "error": "Failed to get global hooks path"}
    else:
        if repo_path is None:
            git_root = _get_git_root()
            if not git_root:
                return {"success": False, "error": "Not in a git repository"}
            repo_path = git_root
        hooks_dir = repo_path / ".git" / "hooks"

    removed = []

    for hook_name in ["pre-commit", "post-commit"]:
        hook_path = hooks_dir / hook_name
        if hook_path.exists():
            try:
                # Check if it's our hook
                content = hook_path.read_text()
                if "Memoriq" in content:
                    hook_path.unlink()
                    removed.append(hook_name)
            except Exception:
                pass

    return {
        "success": True,
        "removed": removed,
        "hooks_dir": str(hooks_dir),
    }


def emit_commit_event(commit_hash: str = None) -> None:
    """Emit a commit event to the integration bus.

    This is called from the post-commit hook.
    """
    config = _load_config()

    if not config.get("enabled", False):
        return

    # Get commit info
    try:
        if not commit_hash:
            result = subprocess.run(
                ["git", "rev-parse", "HEAD"],
                capture_output=True,
                text=True,
                check=True,
            )
            commit_hash = result.stdout.strip()

        result = subprocess.run(
            ["git", "log", "-1", "--pretty=format:%s"],
            capture_output=True,
            text=True,
            check=True,
        )
        commit_message = result.stdout.strip()

        result = subprocess.run(
            ["git", "diff-tree", "--no-commit-id", "--name-only", "-r", commit_hash],
            capture_output=True,
            text=True,
            check=True,
        )
        changed_files = [f.strip() for f in result.stdout.split("\n") if f.strip()]

    except (subprocess.CalledProcessError, FileNotFoundError):
        return

    # Emit event
    bus = get_bus()
    bus.emit("git_commit", {
        "commit_hash": commit_hash,
        "message": commit_message,
        "files": changed_files,
    })


def _handle_event(event: str, payload: dict[str, Any]) -> None:
    """Handle events from the integration bus."""
    # Git hooks don't need to handle bus events directly
    # They run via git commands
    pass


def init() -> None:
    """Initialize the git hooks integration."""
    # Git hooks don't auto-register with the bus
    # They are invoked by git commands
    logger.info("Git hooks integration loaded (use `memoriq git-install-hooks` to install)")


def main():
    """CLI entry point for git hook commands."""
    parser = argparse.ArgumentParser(description="Memoriq Git Hooks")
    subparsers = parser.add_subparsers(dest="command", help="Commands")

    # Install command
    install_parser = subparsers.add_parser("install", help="Install git hooks")
    install_parser.add_argument(
        "--global", "-g",
        action="store_true",
        dest="global_install",
        help="Install to global core.hooksPath",
    )
    install_parser.add_argument(
        "--repo",
        type=Path,
        help="Path to git repository (default: current directory)",
    )

    # Uninstall command
    uninstall_parser = subparsers.add_parser("uninstall", help="Uninstall git hooks")
    uninstall_parser.add_argument(
        "--global", "-g",
        action="store_true",
        dest="global_install",
        help="Uninstall from global core.hooksPath",
    )
    uninstall_parser.add_argument(
        "--repo",
        type=Path,
        help="Path to git repository (default: current directory)",
    )

    # Run pre-commit command (called by hook)
    subparsers.add_parser("run-pre-commit", help="Run pre-commit checks")

    # Emit commit command (called by hook)
    emit_parser = subparsers.add_parser("emit-commit", help="Emit commit event")
    emit_parser.add_argument("commit_hash", nargs="?", help="Commit hash")

    args = parser.parse_args()

    if args.command == "install":
        result = install_hooks(args.repo, args.global_install)
        if result["success"]:
            scope = "globally" if result["global"] else "locally"
            print(f"[Memoriq] Git hooks installed {scope}:")
            for hook in result["installed"]:
                print(f"  - {hook}")
            print(f"Hooks directory: {result['hooks_dir']}")
        else:
            print(f"[Memoriq] Error: {result['error']}", file=sys.stderr)
            return 1

    elif args.command == "uninstall":
        result = uninstall_hooks(args.repo, args.global_install)
        if result["success"]:
            if result["removed"]:
                print("[Memoriq] Git hooks removed:")
                for hook in result["removed"]:
                    print(f"  - {hook}")
            else:
                print("[Memoriq] No Memoriq hooks found to remove")
        else:
            print(f"[Memoriq] Error: {result['error']}", file=sys.stderr)
            return 1

    elif args.command == "run-pre-commit":
        return run_pre_commit()

    elif args.command == "emit-commit":
        emit_commit_event(args.commit_hash)

    else:
        parser.print_help()

    return 0


if __name__ == "__main__":
    sys.exit(main())
